### ISSUE TITLE
error when selecting 'add visibility drivers'

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/mhx2-makehuman-exchange#5]
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\hide.py", line 50, in execute
    addHideDriver(ob, rig)
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\hide.py", line 67, in addHideDriver
    addDriver(rig, clo, "hide", prop, expr = "not(x)")
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\drivers.py", line 44, in addDriver
    fcu = rna.driver_add(path)
TypeError: bpy_struct.driver_add(): property "hide" not found

location: <unknown location>:-1

**Comment by Aranuvir** [comment]
Known issue. I've the tendency to remove that option, because I do not really see a benefit.
Currently MHX has tons of issues that need to be fixed and I don't think it will make much sense to name them one by one. The biggest problem is we need someone who has the time to fix all that stuff...

**Comment by helour** [comment]
@all I made some changes myself (compatibility for Blender 2.80+). You can download the zip file [here](https://www.dropbox.com/s/k4hdlvktf36jeik/import_runtime_mhx2.zip?dl=0).

**Comment by black-punkduck** [comment]
@helour I added these changes to the "official" version now. The blender support for 2.7x I just deleted. Maybe I copy a 2.79 version on my own github repo ... or we keep the original one as well.
