### ISSUE TITLE
Error and mesh import failure when override 'exported rigify' checked

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/mhx2-makehuman-exchange#7]
Error and mesh import failure when override 'exported rigify' checked

Generated <bpy_struct, Object("rig")>
Traceback (most recent call last):
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\importer.py", line 57, in execute
    importMhx2File(self.filepath, cfg, context)
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\importer.py", line 145, in importMhx2File
    build(struct, cfg, context)
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\importer.py", line 230, in build
    rig,parser = buildRig(mhHuman, mhSkel, cfg, context)
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\armature\build.py", line 170, in buildRig
    rig = rigifyMhx(context, parser)
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\import_runtime_mhx2\armature\rigify.py", line 299, in rigifyMhx
    eb.parent = gen.data.edit_bones[Parents[bname]]
KeyError: 'bpy_prop_collection[key]: key "ORG-chest" not found'

location: <unknown location>:-1

location: <unknown location>:-1

Thank you, and be well

**Comment by Aranuvir** [comment]
I won't copy/paste my comment from that last bug report. Rigify does not work atm...
