### ISSUE TITLE
Export GUI Doesn't Load

### ISSUE THREAD

**Issue by YodraB** [makehumancommunity/mhx2-makehuman-exchange#9]
Logs show:
"Exception during event onFileSelected
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
  File "./apps/gui/guiexport.py", line 112, in onFileSelected
  File "plugins/9_export_mhx2/__init__.py", line 52, in export
  File "plugins/9_export_mhx2/mh2mhx2.py", line 41, in <module>
ImportError: No module named uuid"

This makes exporting impossible.

**Comment by Aranuvir** [comment]
update MH.
